export enum ColorScheme {
  Monochromatic = 'Monochromatic',
  Analogous = 'Analogous',
  Complementary = 'Complementary',
  SplitComplementary = 'SplitComplementary',
  Triadic = 'Triadic',
  Tetradic = 'Tetradic',
  GoldenRatio = 'GoldenRatio',
  Fibonacci = 'Fibonacci',
  PentagramStar = 'PentagramStar',
  VesicaPiscis = 'VesicaPiscis',
  FlowerOfLife = 'FlowerOfLife',
  PlatonicSolids = 'PlatonicSolids',
  SpiralOfTheodorus = 'SpiralOfTheodorus',
  MetatronsCube = 'MetatronsCube',
  SeedOfLife = 'SeedOfLife',
  FibonacciSequence = 'FibonacciSequence',
  GoldenSpiral = 'GoldenSpiral',
  MetallicMeans = 'MetallicMeans',
  ContinuedFraction = 'ContinuedFraction',
  GoldenTrisection = 'GoldenTrisection',
  FareySequence = 'FareySequence',
  NobleNumbers = 'NobleNumbers',
  GoldenTriangle = 'GoldenTriangle',
}
